# Generated by Django 5.0.6 on 2024-11-06 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDeComprobacion',
            fields=[
                ('codigoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPartida', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigoCuenta', models.CharField(max_length=255)),
                ('nombreCuenta', models.CharField(max_length=255)),
                ('Cargo', models.FloatField()),
                ('Abono', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentasMayor',
            fields=[
                ('codigoCuentaMayor', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=255, unique=True)),
                ('nombreCuenta', models.CharField(max_length=255)),
                ('naturaleza', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeResultados',
            fields=[
                ('codigoEstadoDeResultado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('utilidadPerdida', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProyecto', models.CharField(max_length=255)),
                ('totalUnidadesAProducir', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('codigoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPartida', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigoCuenta', models.CharField(max_length=255)),
                ('nombreCuenta', models.CharField(max_length=255)),
                ('Cargo', models.FloatField()),
                ('Abono', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentasDetalle',
            fields=[
                ('codigoCuentaDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=255, unique=True)),
                ('nombreCuenta', models.CharField(max_length=255)),
                ('naturaleza', models.CharField(max_length=255)),
                ('codigoCuentaMayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cuentasmayor')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=255)),
                ('puestoEmpleado', models.CharField(max_length=255)),
                ('salarioDiarioEmpleado', models.FloatField()),
                ('diasTrabajadosEmpleado', models.IntegerField()),
                ('codigoDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.departamento')),
            ],
        ),
    ]
