# Generated by Django 5.0.6 on 2024-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_catalogo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasDetalle',
            fields=[
                ('codigoCuentaDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=255)),
                ('nombreCuenta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CuentasMayor',
            fields=[
                ('codigoCuentaMayor', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=255, unique=True)),
                ('nombreCuenta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionCuentas',
            fields=[
                ('codigoRelacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuentaMayor', models.CharField(max_length=255)),
                ('codigoCuentaDetalle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('codigoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPartida', models.IntegerField()),
                ('fecha', models.DateField()),
                ('codigoCuenta', models.CharField(max_length=255)),
                ('nombreCuenta', models.CharField(max_length=255)),
                ('Cargo', models.FloatField()),
                ('Abono', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
