# Generated by Django 5.0.6 on 2024-11-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_balancedecomprobacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=255)),
                ('puestoEmpleado', models.CharField(max_length=255)),
                ('salarioDiarioEmpleado', models.FloatField()),
                ('diasTrabajadosEmpleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeResultados',
            fields=[
                ('codigoEstadoDeResultado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('utilidadPerdida', models.FloatField()),
            ],
        ),
    ]
