# Generated by Django 5.0.6 on 2024-11-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_empleado'),
        ('accounting', '0009_empleado_estadoderesultados'),
    ]

    operations = [
    ]
