# Generated by Django 5.0.6 on 2024-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_departamento_empleado_codigodepartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProyecto', models.CharField(max_length=255)),
                ('totalUnidadesAProducir', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
            ],
        ),
    ]
